repos:
  -   repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
        - id: go-fmt
        - id: go-vet
        - id: go-mod-tidy
#        - id: go-imports
        - id: go-cyclo
          args:
            - -over=10
            - -avg
        - id: validate-toml
        - id: go-critic
        - id: no-go-testing
        - id: go-unit-tests