repos:
  -   repo: https://github.com/tekwizely/pre-commit-golang
      rev: master
      hooks:
        -   id: go-mod-tidy
        -   id: go-mod-tidy-repo

#        -   id: go-test-mod
#        -   id: go-test-pkg

        -   id: go-fmt
#        -   id: go-fmt-repo
