package config

const (
	PIXIV_USER_AGENT          = "PIXIV_USER_AGENT"
	PIXIV_PHPSESSID           = "PIXIV_PHPSESSID"
	PIXIV_DNS_QUERY_URL       = "PIXIV_DNS_QUERY_URL"
	PIXIV_BYPASS_SNI_BLOCKING = "PIXIV_BYPASS_SNI_BLOCKING"
)
